version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-workout-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE=./data/gym.db
    volumes:
      # Сохраняем базу данных на хосте, чтобы данные не терялись при перезапуске
      - ./data:/app/data
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

